[package]
name = "hot_constant"
version = "0.1.0"
edition = "2021"

[dependencies]
linkme = {version ="0.3", optional = true}
notify = {version ="6", optional = true}

[examples]
name = "basic"
path = "examples/basic.rs"


[features]
hot = ["linkme", "notify"]
